### ISSUE TITLE
Crashes when decoding big QR codes

### ISSUE THREAD

**Issue by fpicchi** [yype/QRUtil#1]
As the title says, QRUtil crashes when decoding large QR codes. By that I mean QR codes which contain a lot of data.
Example QR code:
![qr-code](https://user-images.githubusercontent.com/49197860/131672681-fe6fe175-b2e8-426f-b6e0-f1710817e4ce.png)

**Comment by yype** [comment]
Thanks for the report. It should have been fixed by #2.
